[phases.setup]
nixPkgs = [
  "php83",
  "php83Extensions.redis"
]

[phases.install]
cmds = [
  "composer install --ignore-platform-req=ext-mongodb --no-dev --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT"